Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -95,8 +95,14 @@ jobs:
       - name: Extract JAR URLs and download to trivy_scan
         run: |
            mkdir -p trivy_scan
+           # Remove all 'Progress' lines
            sed '/Progress/d' build.log > build_clean.log
-           cat build_clean.log
+
+           # Extract just the JAR URLs from lines containing 'Uploaded to codeartifact:'
+           grep 'Uploaded to codeartifact:' build_clean.log | grep '.jar' | while read -r url; do
+             echo "Downloading: $url"
+             curl -fSL -o "trivy_scan/$(basename "$url")" "$url" && echo "Saved to trivy_scan/" || echo "Failed to download: $url"
+           done
       - name: Install Trivy
         run: |
           curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
